---
- name: Clean K3s Total
  hosts: all
  become: yes
  tasks:
    - shell: k3s-killall.sh 2>/dev/null || true
    - systemd:
        name: k3s
        state: stopped
        enabled: no
    - file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
        - /var/lib/etcd
        - /run/k3s
        - /etc/systemd/system/k3s*
    - systemd:
        daemon_reload: yes
